### PR TITLE
Several fixes to the mock

### PR DESCRIPTION
**Pull request by mattlewis92**
I left joinedRooms as it is to preserve BC, other than that I think everything else is pretty self explanatory.

### CODE REVIEW

**Comment by agconti** [comment]
@mattlewis92 thank you for contributing! Your pull request looks great. @glemmaPaul please review and merge.

**Comment by glemmaPaul** [comment]
SO stupid of me to not respond to this. @mattlewis92 this is such a late response and I'm sorry to have not responded to this. Thank you for this PR, I really appreciate it :+1:

**Comment by mattlewis92** [comment]
No worries :smile: Any chance of pushing a new version with the changes?

**Comment by glemmaPaul** [comment]
@mattlewis92 I'll definitely upload a new one, would love to add this PR #5 to it

**Pull request merged**
